name: GithubCI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # there is no need to install wget, libc, gcc, zlib1g, tar or xz-utils. all of there come with the runner by default
      - name: Install binutils-arm-none-eabi for devkitARM-less build
        run: sudo apt install binutils-arm-none-eabi
      
      # apparently setting an env var in a step will not take effect until the next step, so when setting env vars one cannot depend on vars set previously but in the same step
      - name: Set environment variables
        run: |
          echo "DEVKITPRO=$HOME" >> $GITHUB_ENV
          echo "DEVKITARM=$HOME/devkitARM" >> $GITHUB_ENV
      
      - name: Load and setup devkitARM
        run: |
          wget -nv https://github.com/devkitPro/buildscripts/releases/download/devkitARM_r52/devkitARM_r52-linux.tar.xz https://github.com/devkitPro/devkitarm-rules/releases/download/v1.0.0/devkitarm-rules-1.0.0.tar.xz
          tar xJf devkitARM*.tar.xz -C $DEVKITPRO
          tar xJf devkitarm-rules-*.tar.xz -C $DEVKITARM
      
      - name: Fetch repo
        uses: actions/checkout@master
        
      - name: Build using devkitARM via script
        run: sh build.sh
      - name: Build using devkitARM via Makefile
        run: |
          make clean
          make -j$(nproc) all
      
      - name: Unset environment variables
        run: |
          echo "DEVKITPRO=" >> $GITHUB_ENV
          echo "DEVKITARM=" >> $GITHUB_ENV
          
      - name: Build using binutils-arm-none-eabi via script
        run: sh build.sh
      - name: Build using binutils-arm-none-eabi via Makefile
        run: |
          make clean
          make -j$(nproc) all
