name: GithubCI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get wget, tar, xzip, gcc, libc and zlib1g
        run: sudo apt install wget tar xz-utils gcc-multilib linux-libc-dev zlib1g-dev
      
      # so apparently setting an env var in a step will not take effect until the next step
      - name: Set environment variables
        run: |
          echo "DEVKITPRO=$HOME" >> $GITHUB_ENV
          echo "DEVKITARM=$HOME/devkitARM" >> $GITHUB_ENV
      
      - name: check env vars
        run: |
          echo $DEVKITPRO
          echo $DEVKITARM
      
      - name: Load and setup devkitARM and rules
        run: |
          wget https://github.com/devkitPro/buildscripts/releases/download/devkitARM_r52/devkitARM_r52-linux.tar.xz https://github.com/devkitPro/devkitarm-rules/releases/download/v1.0.0/devkitarm-rules-1.0.0.tar.xz
          echo $DEVKITPRO
          echo $DEVKITARM
          tar vxJf devkitARM*.tar.xz
          tar vxJf devkitarm-rules-*.tar.xz -C $DEVKITARM
        working-directory: $HOME
      
      - name: Fetch repo
        uses: actions/checkout@master
        
      - name: Build via script
        run: sh build.sh
      - name: Build via Makefile
        run: |
          make clean
          make -j4 all
