name: GithubCI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get wget, tar, xzip, gcc, libc and zlib1g
        run: sudo apt install wget tar xz-utils gcc-multilib linux-libc-dev zlib1g-dev
      
      - name: check env vars
        run: |
          echo "::set-env name=DEVKITPRO::$HOME"
          echo "::set-env name=DEVKITARM::$DEVKITPRO/devkitARM"
          echo $DEVKITPRO
          echo $DEVKITARM
      
      - name: Load and setup devkitARM and rules
        run: |
          echo "::set-env name=DEVKITPRO::$HOME"
          echo "::set-env name=DEVKITARM::$DEVKITPRO/devkitARM"
          mkdir -p $DEVKITARM
          wget https://github.com/devkitPro/buildscripts/releases/download/devkitARM_r52/devkitARM_r52-linux.tar.xz
          wget https://github.com/devkitPro/devkitarm-rules/releases/download/v1.0.0/devkitarm-rules-1.0.0.tar.xz
          tar xJf devkitARM*.tar.xz
          tar xJf devkitarm-rules-*.tar.xz -C $DEVKITARM
        working-directory: $HOME
      
      - name: Fetch repo
        uses: actions/checkout@master
        
      - name: Build via script
        run: |
          echo "::set-env name=DEVKITPRO::$HOME"
          echo "::set-env name=DEVKITARM::$DEVKITPRO/devkitARM"
          sh build.sh
      - name: Build via Makefile
        run: |
          echo "::set-env name=DEVKITPRO::$HOME"
          echo "::set-env name=DEVKITARM::$DEVKITPRO/devkitARM"
          make clean
          make -j4 all
