name: GithubCI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEVKITPRO=$HOME
      DEVKITARM=$DEVKITPRO/devkitARM
    steps:
      - name: Get wget, tar, xzip, gcc, libc and zlib1g
        # alternatively one could just "run: sudo apt-get install [packages]"
        run: sudo apt install wget tar xz-utils gcc-multilib linux-libc-dev zlib1g-dev
      
      - name: Setup devkitARM and rules
        run: |
          pushd $HOME
          wget https://github.com/devkitPro/buildscripts/releases/download/devkitARM_r52/devkitARM_r52-linux.tar.xz https://github.com/devkitPro/devkitarm-rules/releases/download/v1.0.0/devkitarm-rules-1.0.0.tar.xz
          tar xJf devkitARM*.tar.xz
          tar xJf devkitarm-rules-*.tar.xz -C $DEVKITARM
          popd
      
      - name: Fetch repo
        uses: actions/checkout@master
        
      - name: Build via script
        run: sh build.sh
      - name: Build via Makefile
        run: |
          make clean
          make -j4 all
