name: GithubCI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEVKITPRO: $HOME
      DEVKITARM: $DEVKITPRO/devkitARM
    steps:
      - name: Setup devkitARM and rules
        run: |
          wget -nv https://github.com/devkitPro/buildscripts/releases/download/devkitARM_r52/devkitARM_r52-linux.tar.xz https://github.com/devkitPro/devkitarm-rules/releases/download/v1.0.0/devkitarm-rules-1.0.0.tar.xz
          tar xJf devkitARM*.tar.xz && tar xJf devkitarm-rules-*.tar.xz -C $DEVKITARM
        working-directory: $HOME
      
      - name: Fetch repo
        uses: actions/checkout@master
        
      - name: Build via script
        run: sh build.sh
      - name: Build via Makefile
        run: |
          make clean
          make -j4 all
